# This file contains the core container parameters. Most of them may be overwritten
# in test environment (see app/config/config_test.yml)

parameters:
    claroline.param.files_directory: "%kernel.root_dir%/../files"
    claroline.param.vendor_directory: "%kernel.root_dir%/../vendor"
    claroline.param.thumbnails_directory: "%claroline.param.web_dir%/thumbnails"
    claroline.param.uploads_directory : "%claroline.param.web_dir%/uploads"
    claroline.param.templates_directory: "%kernel.root_dir%/../templates/"
    claroline.param.default_template: "%kernel.root_dir%/../vendor/claroline/core-bundle/Claroline/CoreBundle/Resources/template/default.zip"
    claroline.param.authentication_directory: "%kernel.root_dir%/config/Authentication"
    claroline.param.platform_config_handler_class: Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler
    claroline.param.platform_options_file: %kernel.root_dir%/config/platform_options.yml
    claroline.param.web_dir: "%kernel.root_dir%/../web"
    #todo: add .param. in the pathaname
    claroline.packages_last_tags_file: "%claroline.cache_dir%/last_tags.cache.ini"
    claroline.composer_log_file: "%kernel.root_dir%/logs/composer.log"
    claroline.ip_white_list_file: "%kernel.root_dir%/config/ips"
    claroline.cache_dir: "%kernel.root_dir%/cache"

