fos_oauth_server:
    db_driver:           orm
    client_class:        Claroline\CoreBundle\Entity\Oauth\Client
    access_token_class:  Claroline\CoreBundle\Entity\Oauth\AccessToken
    refresh_token_class: Claroline\CoreBundle\Entity\Oauth\RefreshToken
    auth_code_class:     Claroline\CoreBundle\Entity\Oauth\AuthCode
