be_simple_sso_auth:
    admin_sso:
        protocol:
            id: cas
            version: 2
        server:
            id: cas
            login_url: http://cas.server.tld/login
            logout_url: http://cas.server.tld/logout
            validation_url: http://cas.server.tld/serviceValidate
